### ISSUE TITLE
Kalibrace senzoru na čáru - motory

### ISSUE THREAD

**Issue by JakubAndrysek** [RoboticsBrno/RB3201-RBControl-Roboruka-library#5]
Kalibrace nepočítá s možným otočením směru otáčení kola. Je tam natvrdo nastavený směr. Pokud však připojím jeden motor naopak. Kalibrace nebude fungovat.

https://github.com/RoboticsBrno/RB3201-RBControl-Roboruka-library/blob/63b0def203e887299588da2e96761e1a490d6eb1/src/roboruka.cpp#L223-L259

**Comment by Tasssadar** [comment]
Opraveno v #2
